# Generated by Django 4.2.1 on 2023-05-15 16:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
